### ISSUE TITLE
Mention adjustment of results when getting dates of Jewish holidays

### ISSUE THREAD

**Issue by tbrowder** [jforget/raku-Date-Calendar-Hebrew#1]
When I use your code to calculate the first day of Hanukkah in the Gregorian calendar (Raku Date type), it always gives me one day later than the results shown on various list of Hanukkah dates for any given year.

I understand about the Hebrew day beginning at local sunset, but does your module make some kind of adjustment for local sunset? As it stands at the moment, I just subtract one day, but I’m not comfortable doing that without some assurance I’m doing the right thing.

Note I am located at UTC-5 (US CDT).

Thanks very much for your work on this module—it’s very useful and good work!

**Comment by jforget** [comment]
The problem of the sunset is mentioned in the module's documentation, both in paragraph "DESCRIPTION" and in paragraph "PROBLEMS AND KNOWN BUGS". As I wrote, "It  is up  to the  user to assert the  need of incrementing  the Hebrew date or  decrementing the Gregorian date if the time of day is in the evening after sunset.", so you do the right thing.

Sorry for being late with my answer, and thanks for your appreciation.

**Comment by tbrowder** [comment]
I know the problem is mentioned, but is it possible to have the module  have a local sunset time input to affect the calculations? My concern is that I might make a mistake if I implement the solution.

I have asked a couple of Jewish acquaintances about my concern: one  doesn't practice the religion and the other, a Rabbi, hasn't responded.

**Comment by jforget** [comment]
I have released version 0.1.0 of all `Date::Calendar::xxx` modules. In the new version, you can add a `daypart`  parameter to the `new` constructor. By using `daypart => after-sunset`, you ensure that the adjustment is done within the `Date::Calendar::Hebrew` class (or any other class which defines days as sunset-to-sunset).

**Comment by tbrowder** [comment]
Great! Now if you could show that used in your example.

**Comment by jforget** [comment]
I have added the example to README.md. Thank you for your interest.

**Comment by tbrowder** [comment]
Thank you very much, Jean! Closing this now.
